linters:
  enable-all: false
  disable-all: true
  enable: # please keep this alphabetized
    - bodyclose # checks if HTTP responses are properly closed
    - containedctx # checks best practice of not storing Context in structs
    - depguard # defines and checks for disallowed package imports
    - errcheck # [default] checks for code issues with error wrapping introduced in Go 1.13
    - errorlint # checks for unchecked error handling
    - gocritic # linter with many check items
    - gofmt # checks if go fmt has been applied
    - goimports # checks if goimports has been applied
    - gosec # checks various security aspects
    - gosimple # [default] checks for unnecessary code patterns
    - govet # [default] official go vet tool
    - ineffassign # [default] checks for unnecessary assignments
    - misspell # spell checker
    - nakedret # checks for naked returns in long functions
    # - paralleltest # checks for tests without t.Parallel() - TODO: enable after adding t.Parallel() to tests
    - rowserrcheck # checks if database/sql Rows errors are properly handled
    - sqlclosecheck # checks if sql.Rows and sql.Stmt are properly closed
    - staticcheck # [default] linter with many check items
    - unconvert # checks for unnecessary type conversions
    - unparam # checks for unused parameters
    - unused # checks for unused variables/constants/functions/types

run:
  timeout: 5m

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: io/ioutil
            desc: The io/ioutil package has been deprecated, see https://go.dev/doc/go1.16#ioutil
  revive:
    rules:
      - name: package-comments
        disabled: true
issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
